# Generated by Django 4.0.2 on 2023-02-24 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_alter_todo_description_alter_todo_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('status', '-updated')},
        ),
    ]
