export const TODO_LIST_REQUEST = 'TODO_LIST_REQUEST'
export const TODO_LIST_SUCCESS = 'TODO_LIST_SUCCESS'
export const TODO_LIST_FAIL = 'TODO_LIST_FAIL'

export const TODO_DETAILS_REQUEST = 'TODO_DETAILS_REQUEST'
export const TODO_DETAILS_SUCCESS = 'TODO_DETAILS_SUCCESS'
export const TODO_DETAILS_FAIL = 'TODO_DETAILS_FAIL'


export const TODO_CREATE_REVIEW_REQUEST = 'TODO_CREATE_REVIEW_REQUEST'
export const TODO_CREATE_REVIEW_SUCCESS = 'TODO_CREATE_REVIEW_SUCCESS'
export const TODO_CREATE_REVIEW_FAIL = 'TODO_CREATE_REVIEW_FAIL'
export const TODO_CREATE_REVIEW_RESET = 'TODO_CREATE_REVIEW_RESET'
